version: '3.5'

services:  
    api-service:  
      container_name: api 
      build: ./api 
      ports: 
        - '8080:8080'  
   
    angular-service:  
      container_name: front  
      build: ./frontend
      depends_on:
        - api-service
      volumes:  
        - './frontend:/usr/src/app' 
      ports: 
        - '4200:4200'  
      command: > 
        bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"